POST http://localhost:3333/videos
Content-Type: application/json


{
    "title": "Jeferson costa",
    "description": "Jeferson + atila + travecao",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/4965c072-8426-46a2-8683-4bc37990f0a1
Content-Type: application/json


{
    "title": "Jeferson costa",
    "description": "So o atila",
    "duration": 180
}


###

DELETE  https://api-node-postgre.onrender.com/videos/
Content-Type: application/json